stages:
  - test
  - sync

.base:
  image: jreinert/crystal-alpine:latest
  before_script:
    - shards install

spec:
  extends: .base
  stage: test
  script:
    - crystal spec

lint:
  extends: .base
  stage: test
  script:
    - bin/ameba

format:
  extends: .base
  stage: test
  script:
    - crystal tool format --check

github sync:
  stage: sync
  variables:
    GIT_SSH_COMMAND: ssh -i deploy_key -o StrictHostKeyChecking=no
  script:
    - git remote add github git@github.com:repomaa/mass_assignable.git
    - git push --all github
  only:
    refs:
      - master
