stages:
  - test
  - sync

.base:
  image: jreinert/crystal-alpine:latest
  before_script:
    - shards install

spec:
  extends: .base
  stage: test
  script:
    - crystal spec

lint:
  extends: .base
  stage: test
  script:
    - bin/ameba

format:
  extends: .base
  stage: test
  script:
    - crystal tool format --check

github sync:
  image: alpine:latest
  stage: sync
  variables:
    GIT_SSH_COMMAND: ssh -i /deploy_key -o StrictHostKeyChecking=no
  before_script:
    - apk update && apk add openssh git
    - touch /deploy_key
    - chmod 600 /deploy_key
    - echo "$DEPLOY_KEY" > /deploy_key
    - git clone --mirror . mirror
  script:
    - cd mirror
    - git remote add github git@github.com:repomaa/mass_assignable.git
    - git push --mirror github
  only:
    refs:
      - master
