stages:
  - test
  - sync

.base:
  image: jreinert/crystal-alpine:latest
  before_script:
    - shards install

spec:
  extends: .base
  stage: test
  script:
    - crystal spec

lint:
  extends: .base
  stage: test
  script:
    - bin/ameba

format:
  extends: .base
  stage: test
  script:
    - crystal tool format --check

github sync:
  image: alpine:latest
  stage: sync
  variables:
    GIT_SSH_COMMAND: ssh -i deploy_key -o StrictHostKeyChecking=no
  before_script:
    - export LOCAL_REPO=$(pwd)
    - apk update && apk add openssh git
    - cd /opt && git clone --mirror "$LOCAL_REPO" "$CI_PROJECT_NAME"
    - cd "/opt/$PROJECT_NAME" && git remote add github git@github.com:repomaa/mass_assignable.git
    - touch "/opt/$PROJECT_NAME/deploy_key"
    - chmod 600 "/opt/$PROJECT_NAME/deploy_key"
    - echo "$DEPLOY_KEY" > "/opt/$PROJECT_NAME/deploy_key"
  script:
    - cd "/opt/$PROJECT_NAME" && git push --mirror github
  only:
    refs:
      - master
